# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
Orchid Env RL Evaluation Environment.

An RL environment where child agents are evaluated on real coding-fix tasks.
An orchestrator manages the task queue; each step() evaluates a submitted
code fix inside an isolated MSB sandbox and returns a reward signal.

Flow::

    obs = env.reset()               # assigned first task (description + broken code)
    while not obs.done:
        fix = agent.solve(obs)      # child agent produces a code fix
        obs = env.step(fix)         # run fix in sandbox, score it, advance task

Reward = tests_passed / tests_total  (0.0 – 1.0 per task)
"""

import base64
import os
import re
from dataclasses import dataclass
from typing import Dict, List, Optional
from uuid import uuid4
from concurrent.futures import ThreadPoolExecutor

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

try:
    from ..models import OrchidAction, OrchidObservation
except ImportError:
    from models import OrchidAction, OrchidObservation

from .sandbox_controller import LocalController

# ---------------------------------------------------------------------------
# Task bank
# ---------------------------------------------------------------------------

@dataclass
class BigDataTask:
    id: str
    description: str
    dataset_path: str
    dataset_lines: int
    ground_truth: str
    task_type: str # 'list' or 'count'

TASK_BANK: List[BigDataTask] = [
    BigDataTask(
        id="extract_anomalies_easy",
        description=(
            "EASY: You are given a massive system log file. "
            "Extract all occurrences of 'EASTER_EGG_ERROR_CODE' values. "
            "Output must be a python list of the string codes found, e.g., ['0x99A', '0x99B']."
        ),
        dataset_path="server/mock_system.log",
        dataset_lines=10003,
        ground_truth="['0x99A', '0x99B', '0x99A']",
        task_type="list"
    ),
    BigDataTask(
        id="count_critical_medium",
        description=(
            "MEDIUM: You are given a massive system log file. "
            "Count the exact total number of 'CRITICAL' level logs in the entire file. "
            "Output must be just the integer count."
        ),
        dataset_path="server/mock_system.log",
        dataset_lines=10003,
        ground_truth="3",
        task_type="count"
    ),
    BigDataTask(
        id="count_by_module",
        description=(
            "MEDIUM: You are given a massive system log file. "
            "Count the total number of logs generated by each module (e.g., 'nginx', 'postgres'). "
            "Assume the log format is '[TIMESTAMP] [HOSTNAME] [MODULE][PID]: [LEVEL] - [MESSAGE]'. "
            "Output must be a Python dictionary mapping the module name (string) to its log count (integer)."
        ),
        dataset_path="server/mock_system.log",
        dataset_lines=10003,
        ground_truth="{'api_server': 2031, 'auth': 1981, 'kernel': 1985, 'nginx': 2013, 'postgres': 1993}",
        task_type="dict"
    ),
    BigDataTask(
        id="count_cache_misses_per_module",
        description=(
            "HARD: You are given a massive system log file. "
            "Find how many times each module experienced a 'Cache miss'. "
            "Output must be a Python dictionary mapping the module name (string) to the count of 'Cache miss' messages (integer). "
            "Only include modules that had at least one cache miss."
        ),
        dataset_path="server/mock_system.log",
        dataset_lines=10003,
        ground_truth="{'api_server': 391, 'auth': 391, 'kernel': 372, 'nginx': 401, 'postgres': 415}",
        task_type="dict"
    ),
    BigDataTask(
        id="json_root_mem_sum",
        description=(
            "HARD: You are given a massive log file (dataset.log). "
            "Some lines contain JSON payloads starting with 'JSON_REPORT: '. "
            "Parse the JSON objects and extract the 'mem' field value for all objects where 'user' is 'root' and 'cpu' > 0.0. "
            "Return the sum of these memory percentages as a single float."
        ),
        dataset_path="server/complex_data.log",
        dataset_lines=10000,
        ground_truth="4.3",
        task_type="count"
    ),
    BigDataTask(
        id="regex_fail_ips",
        description=(
            "HARD: You are given a massive log file (dataset.log). "
            "Use Regex or string manipulation to parse lines starting with 'NETWORK_LOG'. "
            "Find transactions where the ID contains 'FAIL' (e.g., TX-1234-FAIL) AND the 'payload_size' is > 2000 bytes. "
            "Extract the 'origin' IP addresses for these transactions. "
            "Return a sorted Python list of strings containing the unique IPs."
        ),
        dataset_path="server/complex_data.log",
        dataset_lines=10000,
        ground_truth="['10.0.10.87', '10.0.100.114', '10.0.102.153', '10.0.102.183', '10.0.103.20', '10.0.104.11', '10.0.104.19', '10.0.107.176', '10.0.108.180', '10.0.108.231', '10.0.109.104', '10.0.109.130', '10.0.109.48', '10.0.109.82', '10.0.110.125', '10.0.110.204', '10.0.111.196', '10.0.112.9', '10.0.114.141', '10.0.116.81', '10.0.116.98', '10.0.118.171', '10.0.118.79', '10.0.119.139', '10.0.12.205', '10.0.120.95', '10.0.121.209', '10.0.122.180', '10.0.123.143', '10.0.124.194', '10.0.125.135', '10.0.126.196', '10.0.127.31', '10.0.129.175', '10.0.13.233', '10.0.13.238', '10.0.130.224', '10.0.130.75', '10.0.130.83', '10.0.131.234', '10.0.133.161', '10.0.133.236', '10.0.133.3', '10.0.134.157', '10.0.134.199', '10.0.134.208', '10.0.135.136', '10.0.136.137', '10.0.137.59', '10.0.137.61', '10.0.139.154', '10.0.140.202', '10.0.140.218', '10.0.140.95', '10.0.141.200', '10.0.142.193', '10.0.142.38', '10.0.143.192', '10.0.144.176', '10.0.144.200', '10.0.146.161', '10.0.146.183', '10.0.148.11', '10.0.148.238', '10.0.151.100', '10.0.151.122', '10.0.152.233', '10.0.153.145', '10.0.153.52', '10.0.154.24', '10.0.155.114', '10.0.156.219', '10.0.159.240', '10.0.16.177', '10.0.16.74', '10.0.160.134', '10.0.161.214', '10.0.163.139', '10.0.163.221', '10.0.163.83', '10.0.165.158', '10.0.167.169', '10.0.168.35', '10.0.168.46', '10.0.169.162', '10.0.169.170', '10.0.170.175', '10.0.171.17', '10.0.173.162', '10.0.173.64', '10.0.174.38', '10.0.177.179', '10.0.177.237', '10.0.178.105', '10.0.178.249', '10.0.18.214', '10.0.181.50', '10.0.182.171', '10.0.183.170', '10.0.183.29', '10.0.184.86', '10.0.185.106', '10.0.186.20', '10.0.188.171', '10.0.189.209', '10.0.189.210', '10.0.19.191', '10.0.190.106', '10.0.190.115', '10.0.190.145', '10.0.190.196', '10.0.191.132', '10.0.196.116', '10.0.196.126', '10.0.197.109', '10.0.197.239', '10.0.197.91', '10.0.198.116', '10.0.199.181', '10.0.199.201', '10.0.199.219', '10.0.2.10', '10.0.2.249', '10.0.2.41', '10.0.20.94', '10.0.200.87', '10.0.201.194', '10.0.203.202', '10.0.203.38', '10.0.205.119', '10.0.205.227', '10.0.207.154', '10.0.208.154', '10.0.208.168', '10.0.208.28', '10.0.209.199', '10.0.209.76', '10.0.21.1', '10.0.21.191', '10.0.210.197', '10.0.211.180', '10.0.211.56', '10.0.213.15', '10.0.213.32', '10.0.214.104', '10.0.216.32', '10.0.217.30', '10.0.218.178', '10.0.219.147', '10.0.221.227', '10.0.223.104', '10.0.223.163', '10.0.227.35', '10.0.228.35', '10.0.23.196', '10.0.23.198', '10.0.230.164', '10.0.231.80', '10.0.234.248', '10.0.235.230', '10.0.235.44', '10.0.237.106', '10.0.237.109', '10.0.237.181', '10.0.24.3', '10.0.241.156', '10.0.242.128', '10.0.243.94', '10.0.245.147', '10.0.245.235', '10.0.246.184', '10.0.247.97', '10.0.248.116', '10.0.248.195', '10.0.249.167', '10.0.250.177', '10.0.250.224', '10.0.252.226', '10.0.254.145', '10.0.255.173', '10.0.255.2', '10.0.255.47', '10.0.26.165', '10.0.26.31', '10.0.27.4', '10.0.30.234', '10.0.33.51', '10.0.34.70', '10.0.40.142', '10.0.42.75', '10.0.43.36', '10.0.44.48', '10.0.46.57', '10.0.47.125', '10.0.47.207', '10.0.47.96', '10.0.5.121', '10.0.51.1', '10.0.51.64', '10.0.52.208', '10.0.53.102', '10.0.53.107', '10.0.53.162', '10.0.54.11', '10.0.54.229', '10.0.55.108', '10.0.55.176', '10.0.58.21', '10.0.59.1', '10.0.59.79', '10.0.6.156', '10.0.6.221', '10.0.6.26', '10.0.60.108', '10.0.60.19', '10.0.60.4', '10.0.61.141', '10.0.61.254', '10.0.61.33', '10.0.62.146', '10.0.63.120', '10.0.63.168', '10.0.64.164', '10.0.65.24', '10.0.66.155', '10.0.66.158', '10.0.67.100', '10.0.67.120', '10.0.67.122', '10.0.67.227', '10.0.69.101', '10.0.69.228', '10.0.7.18', '10.0.72.206', '10.0.72.231', '10.0.73.13', '10.0.73.216', '10.0.74.29', '10.0.75.12', '10.0.76.43', '10.0.77.88', '10.0.8.157', '10.0.81.205', '10.0.83.145', '10.0.83.236', '10.0.84.64', '10.0.84.85', '10.0.85.105', '10.0.86.169', '10.0.88.11', '10.0.88.133', '10.0.91.252', '10.0.96.215', '10.0.96.225', '10.0.97.88', '10.0.99.2']",
        task_type="list"
    ),
    BigDataTask(
        id="latex_explanation_audit",
        description=(
            "ULTRA-HARD: You are auditing a collection of physics questions (physics_questions.json). "
            "Identify questions where the 'explanation' field contains at least TWO DIFFERENT LaTeX commands "
            "(commands starting with a backslash, e.g., \\lambda and \\det). "
            "Sum the 'answer_label' values for all such questions."
        ),
        dataset_path="server/physics_questions.json",
        dataset_lines=3352,
        ground_truth="57",
        task_type="count"
    ),
    BigDataTask(
        id="cm_shortest_question",
        description=(
            "HARD: Analyze the 'Classical Mechanics' topic in physics_questions.json. "
            "Find the question that has the SHORTEST 'question' string. "
            "In case of a tie in length, choose the one with the lexicographically smallest 'id'. "
            "Return the 'answer_label' (integer) of that question."
        ),
        dataset_path="server/physics_questions.json",
        dataset_lines=3352,
        ground_truth="2",
        task_type="count"
    ),
    BigDataTask(
        id="legacy_print_count",
        description=(
            "EASY: You are auditing a massive 10,000-line legacy Python codebase (legacy_codebase.py). "
            "Use distributed Map-Reduce to count the exact total number of lines that contain the substring 'print(f'Legacy debug: {data}')'. "
            "Output must be a single integer representing the total count."
        ),
        dataset_path="server/legacy_codebase.py",
        dataset_lines=10000,
        ground_truth="53",
        task_type="count"
    ),
    BigDataTask(
        id="legacy_aws_keys",
        description=(
            "HARD: You are auditing a massive legacy Python codebase (legacy_codebase.py) for security vulnerabilities. "
            "Find all hardcoded AWS Access Keys. They follow the pattern 'AKIA' followed by 16 uppercase alphanumeric characters. "
            "Extract these keys and return a sorted Python list of unique strings."
        ),
        dataset_path="server/legacy_codebase.py",
        dataset_lines=10000,
        ground_truth="['AKIA1JGMFQIE7U3WMJE8', 'AKIA1NIQCCQHVE9I6GKN', 'AKIA2MW6KE7MYV173B63', 'AKIA5OTL83OKMZ825EQ5', 'AKIAEQYWNP99QWR5UWFP', 'AKIAIRSJP7YHX89L7ZJM', 'AKIAIW5JY38L9541WO7H', 'AKIAJXIHW1OPSIJQE4YU', 'AKIAM2PZHE4JHZ291R99', 'AKIAQWLDHGZCGB5GJ7SQ', 'AKIAXOJXCZ147DNT15R0', 'AKIAZL5ECD38SD8G1ICM']",
        task_type="list"
    ),
    BigDataTask(
        id="legacy_popen_lines",
        description=(
            "HARD: You are refactoring a massive legacy Python codebase (legacy_codebase.py). "
            "Identify the exact line numbers (1-indexed) where the deprecated 'os.popen' function is called. "
            "Return a sorted Python list of integers representing these line numbers."
        ),
        dataset_path="server/legacy_codebase.py",
        dataset_lines=10000,
        ground_truth="[910, 1164, 4012, 4332, 4790, 6738, 7935]",
        task_type="list"
    ),
    BigDataTask(
        id="legacy_vulnerable_funcs",
        description=(
            "ULTRA-HARD: You are doing a static analysis of a 10,000-line codebase (legacy_codebase.py). "
            "Find all Python functions that contain a call to 'dangerous_global_mutation()'. "
            "Because this is an anomaly, you must track the context (the name of the function, defined by 'def <name>(') that immediately precedes the dangerous call. "
            "Return a sorted Python list of the function names (strings) that contain this vulnerability."
        ),
        dataset_path="server/legacy_codebase.py",
        dataset_lines=10000,
        ground_truth="['vulnerable_function_1265', 'vulnerable_function_1266', 'vulnerable_function_1267', 'vulnerable_function_1268', 'vulnerable_function_1269']",
        task_type="list"
    )
]


# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

class OrchidEnvironment(Environment):
    """
    RL environment for evaluating code-fixing agents.

    The orchestrator (this class) manages a FIFO queue of CodingTasks.
    On each step() a child agent submits a code fix which is executed inside
    isolated MSB sandboxes.
    The reward equals the fraction of tests that pass (0.0 – 1.0).

    Attributes:
        SUPPORTS_CONCURRENT_SESSIONS: allows multiple independent WebSocket
            sessions, each with their own environment instance.
    """

    SUPPORTS_CONCURRENT_SESSIONS: bool = True

    def __init__(self) -> None:
        self._state = State(episode_id=str(uuid4()), step_count=0)
        self._task_queue: List[BigDataTask] = []
        self._current_task: Optional[BigDataTask] = None
        self._sandbox_controller = LocalController()
        self._agent_scores: Dict[str, float] = {}
        self._episode_done: bool = False

    # ------------------------------------------------------------------
    # Environment interface
    # ------------------------------------------------------------------

    def reset(self, seed=None, episode_id=None, **kwargs) -> OrchidObservation:  # type: ignore[override]
        """
        Start a new episode.
        """
        self._state = State(episode_id=str(uuid4()), step_count=0)
        self._task_queue = list(TASK_BANK)
        self._agent_scores = {}
        self._episode_done = False
        self._current_task = self._task_queue.pop(0) if self._task_queue else None
        
        if self._current_task:
            self._sandbox_controller.set_dataset(self._current_task.dataset_path)

        return self._next_task_observation()

    def step(self, action: OrchidAction) -> OrchidObservation:  # type: ignore[override]
        self._state.step_count += 1

        if self._episode_done or self._current_task is None:
            return OrchidObservation(
                task_id="",
                task_description="Episode complete.",
                done=True,
                reward=0.0
            )

        task = self._current_task
        agent_id = action.agent_id or "default"

        # Evaluate the execution graph inside the sandbox
        execution_output, correctness, sub_agent_errors, execution_time = self._evaluate_in_sandbox(action, task.ground_truth, task.task_type)

        # Calculate Decomposition Efficiency
        total_lines_processed = 0
        overlap_penalty = 0
        covered_lines = set()
        
        for sa in action.sub_agents:
            chunk_size = sa.end_line - sa.start_line
            total_lines_processed += chunk_size
            for i in range(sa.start_line, sa.end_line):
                if i in covered_lines:
                    overlap_penalty += 1
                covered_lines.add(i)
                
        total_agents = len(action.sub_agents)
        dataset_lines = task.dataset_lines
        
        # Ideal agents logic: Roughly 1 agent per 2000 lines
        ideal_agents = max(1, dataset_lines // 2000)
        agent_count_penalty = abs(total_agents - ideal_agents) * 0.1
        
        # Overlap penalty (0.0 to 1.0 scale)
        overlap_ratio = overlap_penalty / max(1, dataset_lines)
        
        # Missing lines penalty
        missing_lines = dataset_lines - len(covered_lines)
        missing_ratio = missing_lines / max(1, dataset_lines)
        
        decomposition_score = 1.0 - agent_count_penalty - overlap_ratio - missing_ratio
        decomposition_score = max(0.0, min(1.0, decomposition_score))
        
        # Dynamic Prompt Score: measure word overlap with task description
        prompt_score = 0.0
        if action.sub_agents:
            task_words = set(re.findall(r'\b\w+\b', task.description.lower()))
            stop_words = {"you", "are", "given", "a", "massive", "file", "the", "in", "of", "to", "and", "is", "for", "must", "be", "python", "string", "strings", "list", "dictionary", "integer", "return", "output", "hard", "easy", "medium", "ultra"}
            important_task_words = task_words - stop_words
            
            total_prompt_score = 0
            for sa in action.sub_agents:
                prompt_words = set(re.findall(r'\b\w+\b', sa.role_prompt.lower()))
                overlap = len(important_task_words.intersection(prompt_words))
                # Max score if they mention at least 40% of important keywords
                score = min(1.0, overlap / max(1.0, len(important_task_words) * 0.4))
                total_prompt_score += score
            prompt_score = total_prompt_score / total_agents

        # Calculate Base Reward
        reward = (0.5 * correctness) + (0.3 * decomposition_score) + (0.2 * prompt_score)
        
        # --- Apply Strict Penalties ---
        # 1. Sub-agent tracebacks/errors (punish bad map code)
        if sub_agent_errors > 0:
            reward -= 0.1 * sub_agent_errors
            
        # 2. Synthesis traceback (punish bad reduce code)
        if execution_output and ("Error" in execution_output or "Traceback" in execution_output):
            reward -= 0.3
            
        # 3. Complete failure to answer correctly (punish random trials/hallucinations)
        if correctness == 0.0:
            reward -= 0.2
            
        # 4. Execution Time Penalty (punish slow code)
        time_penalty = execution_time * 0.01
        reward -= time_penalty

        # 5. Step decay to discourage endless looping
        reward -= 0.05 * self._state.step_count

        # Clip reward strictly to [0.0, 1.0] as per requirements
        reward = max(0.0, min(1.0, reward))

        self._agent_scores[agent_id] = self._agent_scores.get(agent_id, 0.0) + reward

        feedback = (
            f"[{agent_id}] Map-Reduce Execution:\n"
            f"  - Sub-agents spawned: {total_agents} (Ideal: {ideal_agents})\n"
            f"  - Failed Sub-agents: {sub_agent_errors}\n"
            f"  - Execution Time: {execution_time:.2f}s (Penalty: -{time_penalty:.2f})\n"
            f"  - Decomposition Score: {decomposition_score:.2f} (Overlap: {overlap_penalty}, Missing: {missing_lines})\n"
            f"  - Prompt Quality: {prompt_score:.2f}\n"
            f"  - Correctness: {correctness:.2f}\n"
            f"Total Step Reward: {reward:.2f}\n"
            f"Output:\n{execution_output}"
        )

        # Advance Task
        done = False
        completed_task_id = self._current_task.id
        if self._task_queue:
            self._current_task = self._task_queue.pop(0)
            self._sandbox_controller.set_dataset(self._current_task.dataset_path)
            sample = self._get_dataset_sample(self._current_task.dataset_path)
            next_task_desc = f"{self._current_task.description}\n\nDataset Sample (first 5 lines):\n```\n{sample}\n```"
        else:
            self._current_task = None
            self._episode_done = True
            done = True
            next_task_desc = ""

        return OrchidObservation(
            task_id=self._current_task.id if self._current_task else "",
            task_description=next_task_desc,
            dataset_path=self._current_task.dataset_path if self._current_task else "",
            dataset_lines=self._current_task.dataset_lines if self._current_task else 0,
            execution_output=execution_output,
            correctness_score=correctness,
            decomposition_score=decomposition_score,
            prompt_score=prompt_score,
            score=reward,
            feedback=feedback,
            messages=[{"category": "grader", "content": feedback}],
            done=done,
            reward=reward,
            metadata={
                "agent_id": agent_id,
                "agent_scores": self._agent_scores,
                "step": self._state.step_count,
                "completed_task_id": completed_task_id,
            },
        )

    @property
    def state(self) -> State:
        return self._state

    # ------------------------------------------------------------------
    # Orchestrator helpers
    # ------------------------------------------------------------------

    def _get_dataset_sample(self, filepath: str, num_lines: int = 5) -> str:
        """Returns a string containing the first `num_lines` of the dataset."""
        if not os.path.exists(filepath):
            return "Sample unavailable: File not found."
        try:
            with open(filepath, 'r') as f:
                lines = [next(f).strip() for _ in range(num_lines)]
            return "\n".join(lines)
        except StopIteration:
            return "Sample unavailable: File is empty or has fewer than 5 lines."
        except Exception as e:
            return f"Sample unavailable: Error reading file ({e})"

    def _next_task_observation(self) -> OrchidObservation:
        """Assign the next task from the queue and return the opening observation."""
        if not self._current_task:
            self._episode_done = True
            return OrchidObservation(
                task_id="",
                task_description="No tasks available.",
                done=True,
                reward=0.0,
            )

        sample = self._get_dataset_sample(self._current_task.dataset_path)
        desc_with_sample = f"{self._current_task.description}\n\nDataset Sample (first 5 lines):\n```\n{sample}\n```"

        return OrchidObservation(
            task_id=self._current_task.id,
            task_description=desc_with_sample,
            dataset_path=self._current_task.dataset_path,
            dataset_lines=self._current_task.dataset_lines,
            messages=[{"category": "system", "content": desc_with_sample}],
            done=False,
            reward=0.0,
        )

    # ------------------------------------------------------------------
    # Sandbox execution
    # ------------------------------------------------------------------

    def _evaluate_in_sandbox(self, action: OrchidAction, ground_truth: str, task_type: str) -> tuple[str, float, int, float]:
        import time
        sub_outputs = [None] * len(action.sub_agents)
        
        filename = os.path.basename(self._current_task.dataset_path) if self._current_task else "dataset.log"
        
        def run_sub_agent(idx, sub_agent):
            agent_runner = (
                "import sys, json\n"
                f"with open('/data/{filename}', 'r') as f:\n"
                f"    lines = f.readlines()[{sub_agent.start_line}:{sub_agent.end_line}]\n"
                "chunk_data = ''.join(lines)\n\n"
                f"{sub_agent.python_code}\n"
            )
            response = self._sandbox_controller.run_code(agent_runner)
            return idx, response

        start_time = time.time()

        # 1. Map Phase: Execute all sub-agents concurrently using ThreadPoolExecutor
        with ThreadPoolExecutor(max_workers=10) as executor:
            futures = [executor.submit(run_sub_agent, idx, sa) for idx, sa in enumerate(action.sub_agents)]
            for future in futures:
                try:
                    idx, response = future.result()
                    sub_outputs[idx] = response
                except Exception as e:
                    pass

        # Count sub-agent errors
        sub_agent_errors = sum(1 for out in sub_outputs if isinstance(out, str) and ("Error" in out or "Traceback" in out))

        # 2. Reduce Phase: Run the synthesis code
        escaped_outputs = base64.b64encode(repr(sub_outputs).encode()).decode()
        
        synth_runner = (
            "import base64, ast, sys\n"
            f"sub_outputs = ast.literal_eval(base64.b64decode('{escaped_outputs}').decode())\n\n"
            f"{action.synthesis_code}\n"
        )
        
        final_output = self._sandbox_controller.run_code(synth_runner)
        
        end_time = time.time()
        execution_time = end_time - start_time
            
        # 3. Evaluate Correctness (Partial Progress Grader)
        correctness = 0.0
        try:
            if "Error" in final_output or "Traceback" in final_output:
                correctness = 0.0
            else:
                import ast
                import re
                import difflib
                truth_val = ast.literal_eval(ground_truth)
                try:
                    pred_val = ast.literal_eval(final_output)
                except:
                    # Try to extract a structure if literal_eval fails
                    try:
                        match = re.search(r'(\[.*\]|\{.*\})', final_output, re.DOTALL)
                        if match:
                            pred_val = ast.literal_eval(match.group(1))
                        elif task_type == "count":
                            nums = re.findall(r'-?\d+\.?\d*', final_output)
                            pred_val = float(nums[-1]) if nums else final_output
                        else:
                            pred_val = final_output
                    except:
                        pred_val = final_output # fallback to string
                
                if task_type == "list" and isinstance(truth_val, list):
                    if not isinstance(pred_val, list):
                        pred_val = [pred_val] # Force to list for comparison if it failed parsing
                    # Jaccard-like overlap for partial credit
                    truth_set = set(str(x).strip() for x in truth_val)
                    pred_set = set(str(x).strip() for x in pred_val)
                    if not truth_set and not pred_set:
                        correctness = 1.0
                    else:
                        intersection = truth_set.intersection(pred_set)
                        union = truth_set.union(pred_set)
                        correctness = len(intersection) / len(union)
                elif task_type == "count":
                    # Distance-based partial credit for counts
                    try:
                        pred_count = float(pred_val)
                        truth_count = float(truth_val)
                        diff = abs(pred_count - truth_count)
                        correctness = max(0.0, 1.0 - (diff / max(1.0, truth_count)))
                    except:
                        correctness = 0.0
                elif task_type == "dict" and isinstance(truth_val, dict) and isinstance(pred_val, dict):
                    # Partial credit: % of keys present, and if present, closeness of values
                    score = 0.0
                    for k, v_truth in truth_val.items():
                        if k in pred_val:
                            v_pred = pred_val[k]
                            try:
                                if isinstance(v_truth, (int, float)):
                                    diff = abs(float(v_pred) - float(v_truth))
                                    score += max(0.0, 1.0 - (diff / max(1.0, float(v_truth))))
                                elif str(v_truth).strip() == str(v_pred).strip():
                                    score += 1.0
                                else:
                                    # string similarity fallback
                                    sim = difflib.SequenceMatcher(None, str(v_truth).strip(), str(v_pred).strip()).ratio()
                                    score += sim
                            except:
                                pass
                    correctness = score / max(1, len(truth_val))
                else:
                    # Fallback string similarity
                    truth_str = str(truth_val).strip()
                    pred_str = str(pred_val).strip()
                    if truth_str == pred_str:
                        correctness = 1.0
                    else:
                        correctness = difflib.SequenceMatcher(None, truth_str, pred_str).ratio()
        except Exception as e:
            print(f"Grader exception: {e}")
            correctness = 0.0
            
        return final_output, correctness, sub_agent_errors, execution_time
